### ISSUE TITLE
Unfortunately in Maya the camera does not match photos that have a three-point perspective. 

### ISSUE THREAD

**Issue by mehraneftekari2021** [JustinPedersen/maya_fspy#10]
Hi
@JustinPedersen96 
Unfortunately in Maya the camera does not match photos that have a three-point perspective. Works very well in blender
![image](https://user-images.githubusercontent.com/81689127/123499127-a68ac100-d649-11eb-80dd-a8d83ee68b87.png)
![image](https://user-images.githubusercontent.com/81689127/123499449-084c2a80-d64c-11eb-9ecf-a362071ea4c6.png)
[Ref.zip](https://github.com/JustinPedersen/maya_fspy/files/6719467/Ref.zip)

**Comment by JustinPedersen96** [comment]
Thanks for the info and pictures! 
Could you let me know what the AOV/ FOV is on your Blender camera?

**Comment by mehraneftekari2021** [comment]
Hi
![image](https://user-images.githubusercontent.com/81689127/123620050-100ff880-d81f-11eb-8810-713ccf0f05f1.png)
![image](https://user-images.githubusercontent.com/81689127/123620119-1e5e1480-d81f-11eb-9fc9-6a188603783b.png)
