### ISSUE TITLE
support for Maya 2023

### ISSUE THREAD

**Issue by kaimano** [JustinPedersen/maya_fspy#14]
Hi, first congratulation for the great job you done!
Normally I use 2020 version of maya, but I started to try 2023 version but, unfortunately fspy wont work in 2023, i give this error:

# Error: ModuleNotFoundError: file C:\Users/*****/Documents/maya/2023/scripts\maya_fspy\ui.py line 22: No module named 'pymel'

Thanks.

**Comment by kaimano** [comment]
SOLVED
In maya 2023, for some reason, pymel was not installed.
Simply follow this guide to solve:
https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2022/ENU/Maya-Scripting/files/GUID-2AA5EFCE-53B1-46A0-8E43-4CD0B2C72FB4-htm.html

**Comment by JustinPedersen** [comment]
Just noting this here, there is another branch on the Repo called V2 where I've completely removed all the PyMel. Please feel free to give it a go and let me know if you find any issues with it. 

Thanks!
