### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by marckrieger** [JustinPedersen/maya_fspy#15]
Error: ModuleNotFoundError: file C:\Users/user/Documents/maya/2022/scripts\maya_fspy\ui.py line 22: No module named 'pymel'

**Comment by JustinPedersen** [comment]
Hi there 

Your Maya install most likely hasn't been installed with PyMel included. 

I have a work in progress v2 of the script where I have removed all PyMel and reverted to only using cmds. You can find it here but there are likely still issues with that build. 

https://github.com/JustinPedersen/maya_fspy/tree/v2.0.0

Alternatively you would need to re-install your Maya and make sure PyMel is ticked on during that install process.
