### ISSUE TITLE
Pymel?

### ISSUE THREAD

**Issue by ianim8er** [JustinPedersen/maya_fspy#20]
Maya 2022 I get this error trying to run python/shelf button:
# Error: ModuleNotFoundError: file C:/Users/user.name/Documents/maya/2022/scripts\maya_fspy\ui.py line 22: No module named 'pymel' # 
The pymel is the issue I think.

Thanks!

**Comment by JustinPedersen** [comment]
Yes pymel is the issue. 

You'll need to pip install it into your instance of Maya. 

If you are on windows you can do the following: 
1. Open Windows Power Shell. Can search for it in the start bar. 
2. Paste this command in and run. 

`& "C:\Program Files\Autodesk\Maya2022\bin\mayapy.exe" -m pip install pymel`

I am assuming you have maya installed in the default location, if not just update the path above. 

This should install PyMel into your instance of Maya. Restart and the script should work. Maya as of 2022 I believe doesn't ship with PyMel any more. If I have time in future I'd like to re-write the script in CMDS and remove this dependency.

**Comment by ianim8er** [comment]
For Maya 2022:

ERROR: Could not find a version that satisfies the requirement pymel (from versions: none)
ERROR: No matching distribution found for pymel
There is more to the error, I just copied paste the one in red.
I wonder if its an admin issue?

**Comment by ianim8er** [comment]
I also have older versions on same system.
Do I just change the year?
I also see both mayapy and mayapy2 in the bin.

**Comment by JustinPedersen** [comment]
Depends what year of Maya you'd like to use the tool in. I could be mistaken but Maya might not allow pip install on 2022, but they do on 2023 and 2024. 

I believe 2022, you might need to google how to handle installing Pymel there. 

The Mayapy2 is Python2. 2022 is where Maya moved to Python 3 but kept support for Py2. 

If all else fails, I had a branch of this repo where I removed all of the PyMel but it is untested. 
https://github.com/JustinPedersen/maya_fspy/tree/v2.0.0
