### ISSUE TITLE
Support multiple Maya scene up configurations

### ISSUE THREAD

**Issue by JustinPedersen** [JustinPedersen/maya_fspy#4]
From user: @Squall789 

> One thing I wondered is, I used Unreal often, so my Maya axis are using Z as up (though I changed it to Y up for testing this script), would it be possible to add an option, if it's even needed, to correctly rotate the group to the Z up axis if that is the users configuration.

**Comment by Squall789** [comment]
Are there any updates on supporting Z-up configuration within Maya?
I might be premature as this might be a more complex issue than I'm assuming.

**Comment by JustinPedersen96** [comment]
I had a look at this and it can be done simply be changing the settings in FSpy to match the orientation in maya that you want. 

These were my FSPY settings
![fspy_settings](https://user-images.githubusercontent.com/62013683/116665753-6c2edb80-a99a-11eb-9e02-be6c401af172.png)

Image used: 
![test_image_02](https://user-images.githubusercontent.com/62013683/116665813-810b6f00-a99a-11eb-9064-fc854c1f80f6.png)

Results in Maya with orientation set to Z up.
![fspy_maya_settings](https://user-images.githubusercontent.com/62013683/116665841-88327d00-a99a-11eb-9ce0-21ff74531ad5.png)

Will close this issue, but please feel free to open again if this doesn't solve your issue.
