### ISSUE TITLE
any plan to support maya2022 python3 ?

### ISSUE THREAD

**Issue by kloworks** [JustinPedersen/maya_fspy#6]
hi, 
its work fine with 2020.
I already start using 2022 so is there plan to support it since it use python3

big thanks

**Comment by JustinPedersen96** [comment]
Heya. I haven't tested for py3 yet. Will give it a go and see if it needs any tweaking.

**Comment by kloworks** [comment]
Cool man thanks alot can't wait to test it out.

+ I notice in maya 2020 still off and not perfect as blender
maybe because its different version.
blender:
https://imgur.com/OXUNzGh
maya:
https://imgur.com/90GrvIz

**Comment by JustinPedersen96** [comment]
Hmm that might be related to your camera focal length. At present my fspy doesn't set it all up on the camera properly, still another issue I need to find time for 😓

**Comment by JustinPedersen96** [comment]
I've added support for py3 in the latest release. Please feel free to re-open if  there are any issues :)
